-- Minimal seed data (expand as desired)
insert into public.hsk_words (hanzi, pinyin, english, level) values
  ('你好', 'nǐ hǎo', 'hello', 1),
  ('谢谢', 'xiè xie', 'thank you', 1),
  ('是', 'shì', 'to be', 1),
  ('不', 'bù', 'no / not', 1),
  ('我', 'wǒ', 'I / me', 1),
  ('我们', 'wǒ men', 'we / us', 1),
  ('你', 'nǐ', 'you', 1),
  ('他', 'tā', 'he / him', 1),
  ('她', 'tā', 'she / her', 1),
  ('再见', 'zài jiàn', 'goodbye', 1),

  ('因为', 'yīn wèi', 'because', 2),
  ('所以', 'suǒ yǐ', 'therefore', 2),
  ('但是', 'dàn shì', 'but', 2),
  ('可能', 'kě néng', 'maybe / possible', 2),
  ('觉得', 'jué de', 'to feel / think', 2),
  ('开始', 'kāi shǐ', 'to start', 2),
  ('结束', 'jié shù', 'to end', 2),
  ('帮助', 'bāng zhù', 'to help', 2),
  ('问题', 'wèn tí', 'question / problem', 2),
  ('回答', 'huí dá', 'to answer', 2),

  ('准备', 'zhǔn bèi', 'to prepare', 3),
  ('计划', 'jì huà', 'plan', 3),
  ('结果', 'jié guǒ', 'result', 3),
  ('办法', 'bàn fǎ', 'method', 3),
  ('情况', 'qíng kuàng', 'situation', 3),
  ('如果', 'rú guǒ', 'if', 3),
  ('当然', 'dāng rán', 'of course', 3),
  ('必须', 'bì xū', 'must', 3),
  ('应该', 'yīng gāi', 'should', 3),
  ('终于', 'zhōng yú', 'finally', 3),

  ('环境', 'huán jìng', 'environment', 4),
  ('经验', 'jīng yàn', 'experience', 4),
  ('责任', 'zé rèn', 'responsibility', 4),
  ('保证', 'bǎo zhèng', 'to guarantee', 4),
  ('关系', 'guān xì', 'relationship', 4),
  ('建议', 'jiàn yì', 'suggestion', 4),
  ('改变', 'gǎi biàn', 'to change', 4),
  ('提高', 'tí gāo', 'to improve', 4),
  ('减少', 'jiǎn shǎo', 'to reduce', 4),
  ('影响', 'yǐng xiǎng', 'to affect', 4),

  ('措施', 'cuò shī', 'measure (step)', 5),
  ('现象', 'xiàn xiàng', 'phenomenon', 5),
  ('程度', 'chéng dù', 'degree / extent', 5),
  ('稳定', 'wěn dìng', 'stable', 5),
  ('资源', 'zī yuán', 'resources', 5),
  ('压力', 'yā lì', 'pressure', 5),
  ('效率', 'xiào lǜ', 'efficiency', 5),
  ('传统', 'chuán tǒng', 'tradition', 5),
  ('策略', 'cè lüè', 'strategy', 5),
  ('风险', 'fēng xiǎn', 'risk', 5),

  ('趋势', 'qū shì', 'trend', 6),
  ('逻辑', 'luó jí', 'logic', 6),
  ('结构', 'jié gòu', 'structure', 6),
  ('本质', 'běn zhì', 'essence', 6),
  ('假设', 'jiǎ shè', 'assumption', 6),
  ('结论', 'jié lùn', 'conclusion', 6),
  ('背景', 'bèi jǐng', 'background', 6),
  ('因素', 'yīn sù', 'factor', 6),
  ('观点', 'guān diǎn', 'viewpoint', 6),
  ('方案', 'fāng àn', 'plan / proposal', 6),

  ('模糊', 'mó hu', 'vague', 7),
  ('细节', 'xì jié', 'detail', 7),
  ('协调', 'xié tiáo', 'to coordinate', 7),
  ('完善', 'wán shàn', 'to perfect / improve', 7),
  ('维护', 'wéi hù', 'to maintain', 7),
  ('综合', 'zōng hé', 'comprehensive', 7),
  ('限制', 'xiàn zhì', 'restriction', 7),
  ('扩展', 'kuò zhǎn', 'to expand', 7),
  ('评估', 'píng gū', 'to evaluate', 7),
  ('优化', 'yōu huà', 'to optimize', 7),

  ('边界', 'biān jiè', 'boundary', 8),
  ('抽象', 'chōu xiàng', 'abstract', 8),
  ('悖论', 'bèi lùn', 'paradox', 8),
  ('演化', 'yǎn huà', 'evolution', 8),
  ('推导', 'tuī dǎo', 'to derive', 8),
  ('映射', 'yìng shè', 'mapping', 8),
  ('约束', 'yuē shù', 'constraint', 8),
  ('语境', 'yǔ jìng', 'context', 8),
  ('范畴', 'fàn chóu', 'category', 8),
  ('权衡', 'quán héng', 'trade-off', 8),

  ('熵', 'shāng', 'entropy', 9),
  ('涌现', 'yǒng xiàn', 'emergence', 9),
  ('诠释', 'quán shì', 'to interpret', 9),
  ('辩证', 'biàn zhèng', 'dialectical', 9),
  ('先验', 'xiān yàn', 'a priori', 9),
  ('后验', 'hòu yàn', 'a posteriori', 9),
  ('归纳', 'guī nà', 'induction', 9),
  ('演绎', 'yǎn yì', 'deduction', 9),
  ('同构', 'tóng gòu', 'isomorphism', 9),
  ('范式', 'fàn shì', 'paradigm', 9)
on conflict do nothing;

